name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: "Ruby ${{ matrix.ruby-version }}: ${{ matrix.runs-on }}"
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
        runs-on:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Build
        run: |
          cd ext/mysql2-replication
          ruby extconf.rb
          make -j$(nproc)
      # - name: Test
      #   run: |
      #     bundle exec ruby test/run.rb
